apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
  finalizers:
  - kubernetes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: courses-service
  name: courses-service
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: courses-service
    spec:
      containers:
      - image: andipansa/courses-service:1.0.0
        name: courses-service

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: courses-service
  name: courses-service
  namespace: test
spec:
  ports:
  - port: 8080
  selector:
    app: courses-service

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: courses-service
  name: courses-service
  namespace: test
spec:
  rules:
  - host: test.dev.pansa.pl
    http:
      paths:
      - backend:
          serviceName: courses-service
          servicePort: 8080
        path: /
        pathType: ImplementationSpecific
